default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_USER'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exchange_office_development

test:
  <<: *default
  database: exchange_office_test

production:
  <<: *default
  database: exchange_office_production
  username: exchange_office
  password: <%= ENV['EXCHANGE_OFFICE_DATABASE_PASSWORD'] %>
