default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: p@$$w0rd
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exchange_office_dev3

test:
  <<: *default
  database: exchange_office_testdb

production:
  <<: *default
  database: exchange_office_production
  username: exchange_office
  password: <%= ENV['EXCHANGE_OFFICE_DATABASE_PASSWORD'] %>
